$(document).ready(
    function(){
        $("body").css("display", "none")
        $("body").fadeIn(2000);
        $(".left").mouseenter(
            function(){
                $(this).addclass(".hover-left");
            }
        );
        $(".left").mouseleave(
            function(){
                $(this).removeclass(".hover-left");
            }
        );
        $(".right").mouseenter(
            function(){
                $(this).addclass(".hover-right");
            }
        );
        $(".right").mouseleave(
            function(){
                $(this).removeclass(".hover-right");
            }
        );
    }
);